sudo: true
dist: trusty
branches:
  only:
    - travis-build

jobs:
  include:
    - stage: Setup database
      script: bundle exec rake db:create db:schema:load
    - stage: test
      script: bundle exec rake test
