sudo: true
dist: trusty
branches:
  only:
    - travis-build

jobs:
  include:
    - stage: docker compose up
      script: docker-compose up
    - stage: docker test
      script: docker-compose run web rake test
