sudo: true
dist: trusty
branches:
  only:
    - travis-build
cache: bundler

jobs:
  include:
    - stage: Setup and Test application
      script: |
        bundle exec rake db:create db:schema:load
        bundle exec rake test
