---
version: '3'
services:
  web:
    environment:
      - PG=pg
      - POSTGRES='postgres'
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - pg
    command: ["./wait-for-it.sh", pg, "--", "./fire-up-rails.sh"]

  pg:
    image: postgres:9.6
    ports:
      - "5432:5432"
