version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.6
    working_directory: ~/excella-feedback
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/excella-feedback/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle
  rake_test:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.6
    working_directory: ~/excella-feedback
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake test

  deploy:
    machine:
      enabled: true
    working_directory: ~/excella-feedback
    environment:
      - HEROKU_APP: ancient-sea-94054
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - run:
          name: Setup heroku
          command: bash .circleci/setup-heroku-wf.sh
      - run:
          name: Deploy to heroku
          command: |
            git push heroku workflow:master
            heroku run rake db:migrate
            sleep 5 # sleep to wait for dynos
            heroku restart

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: workflow
      - rake_test:
          requires:
            - build
          filters:
            branches:
              only: workflow
      - deploy:
          requires:
            - rake_test
          filters:
            branches:
              only: workflow
