version: 2.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
      - image: circleci/postgres:9.6
    working_directory: ~/excella-feedback
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/excella-feedback/vendor/bundle
      - persist_to_workspace:
          root: .
          paths: vendor/bundle

  rake_test:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
        environment:
          - PG: localhost
          - POSTGRES: postgres
          - RAILS_ENV: test
          - RACK_ENV: test
      - image: circleci/postgres:9.6
        environment:
          - POSTGRES_USER: postgres
          - POSTGRES_DB: feedback_app_test
    working_directory: ~/excella-feedback
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - run: bundle --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake test

  deploy-to-dev:
    machine:
      enabled: true
    working_directory: ~/excella-feedback
    environment:
      - HEROKU_APP: ancient-sea-94054
    steps:
      - checkout
      - attach_workspace:
          at: ~/excella-feedback
      - run:
          name: Setup heroku
          command: bash .circleci/setup-heroku-wf.sh
      - run:
          name: Deploy to heroku
          command: |
            git push heroku workflow:master
            heroku run rake db:migrate
            sleep 5 # sleep to wait for dynos
            heroku restart

  deploy-to-prod:
    machine:
      enabled: true
    working_directory: ~/excella-feedback
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo rm -rf /usr/bin/completion
            sudo mv -f /tmp/docker/* /usr/bin
      - run:
          name: Build and push new image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t taejunyun/excella-fb:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push taejunyun/excella-fb:$TAG
      - deploy:
          name: Deploy development to AWS
          command: |
            .circleci/deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      # - build:
      #     filters:
      #       branches:
      #         only: workflow
      # - rake_test:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: workflow
      # - deploy-to-dev:
      #     requires:
      #       - rake_test
      #     filters:
      #       branches:
      #         only: workflow
      # - hold:
      #     type: approval
      #     requires:
      #       - deploy-to-dev
      #     filters:
      #       branches:
      #         only: workflow
      - deploy-to-prod:
          # requires:
          #   - hold
          filters:
            branches:
              only: workflow
